[versions]
androidx-compose = "1.5.0"
kotlin = "1.9.0"
kotlinx-serialization = "1.5.1"
sqldelight = "2.0.0"
okhttp = "4.11.0"

[libraries]
androidGradlePlugin = "com.android.tools.build:gradle:8.1.0"

androidx-activity-compose = "androidx.activity:activity-compose:1.7.2"
# This isn't strictly used, but allows Renovate to see us using the Compose Compiler artifact
androidx-compose-compiler = "androidx.compose.compiler:compiler:1.5.1"
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-work-runtime = "androidx.work:work-runtime-ktx:2.8.1"

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serializationPlugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

retrofit-core = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit-kotlinxSerializationConverter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:1.0.0"

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

spotlessPlugin = "com.diffplug.spotless:spotless-plugin-gradle:6.20.0"

sqldelight-plugin = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqldelight" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
